# fly.toml app configuration file generated for portuprep on 2023-10-29T13:19:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "portuprep"
primary_region = "yyz"
kill_signal = "SIGTERM"
swap_size_mb = 512

[mounts]
  source="portuprep"
  destination="/mnt/portuprep"

[build]

[deploy]

[env]
  PHX_HOST = "portuprep.com"
  PORT = "8080"
  DATABASE_PATH = "/mnt/portuprep/portuprep.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
